baseURL = "http://idnex.github.io"
languageCode = "en-us"
title = "IDneX"
theme="archie"
copyright = "© IDneX"
# Code Highlight
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

paginate=3 # articles per page

[params]
	mode="toggle" # color-mode → light,dark,toggle or auto
	useCDN=false # don't use CDNs for fonts and icons, instead serve them locally.
	subtitle = "aryaweebs"

# Social Tags

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/idnex"

[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://twitter.com/pramdka/"

[[params.social]]
name = "Facebook"
icon = "facebook"
url = "https://facebook.com/pramudika13"

# Main menu Items

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4